services:  

  rtcstats_server:
    container_name: rtcstats_server
    build:
      context: ./rtcstats-server
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
      - 8095:8095
    volumes:
      - ./rtcstats-server/certs:/rtcstats-server/certs
    environment:
      # For AWS credentials
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_ENDPOINT_URL=http://localstack:4566

      # Localstack
      - LOCALSTACK_ENDPOINT=http://localstack:4566

      # rtcstats-server: server
      - RTCSTATS_LOG_LEVEL
      - RTCSTATS_ENVIRONMENT
      - RTCSTATS_KEYPATH=./certs/key.pem
      - RTCSTATS_CERTPath=./certs/cert.pem
      - RTCSTATS_TEMPPATH=temp
      - RTCSTATS_HTTPS=true
      - RTCSTATS_SKIP_LOAD_BALANCER_IP
      - RTCSTATS_JSON_CONSOLE_LOG

      # rtcstats-server: amplitude
      # - RTCSTATS_AMPLITUDE_KEY=

      # rtcstats-server: firehose
      - RTCSTATS_FIREHOSE_AWS_REGION
      - RTCSTATS_FIREHOSE_MEETING_STREAM
      - RTCSTATS_FIREHOSE_PC_STREAM
      - RTCSTATS_FIREHOSE_TRACKS_STREAM
      - RTCSTATS_FIREHOSE_E2E_PING_STREAM
      - RTCSTATS_FIREHOSE_FACE_LANDMARKS_STREAM
      - RTCSTATS_FIREHOSE_MEETING_EVENT_STREAM

      # rtcstats-server: s3
      - RTCSTATS_S3_ACCESSKEYID
      - RTCSTATS_S3_SECRETACCESSKEY
      - RTCSTATS_S3_AWS_REGION=us-east-1
      - RTCSTATS_S3_BUCKET=jitsi-micros-rtcstats-server
      - RTCSTATS_S3_USEIAMAUTH=true
      - RTCSTATS_S3_SIGNEDLINKEXPIRATIONSEC

      # rtcstats-server: dynamo
      - RTCSTATS_METADATA_TABLE=rtcstats-meta-table-local

      # rtcstats-server: webhooks
      - RTCSTATS_WEBHOOK_ENDPOINT
      - RTCSTATS_JWT_AUDIENCE
      - RTCSTATS_JWT_ISSUER

      # rtcstats-server: secretmanager
      - RTCSTATS_AWS_SECRET_REGION
      - RTCSTATS_JWT_SECRET_ID

    depends_on:
      rtcstats_initialize:
        condition: service_completed_successfully


  rtc_visualizer:
    container_name: rtc_visualizer
    build:
      context: ./rtc-visualizer
      dockerfile: ./Dockerfile
    ports:
      - 8087:8087
    volumes:
      - ./rtc-visualizer/.data:/rtc-visualizer/.data
    environment:
      # For AWS credentials
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_ENDPOINT_URL=http://localstack:4566

      # Localstack
      - LOCALSTACK_ENDPOINT=http://localstack:4566

      # rtc-visualizer
      - AWS_REGION=us-east-1
      - RTCSTATS_S3_BUCKET=jitsi-micros-rtcstats-server
      - RTCSTATS_METADATA_TABLE=rtcstats-meta-table-local
      - RTCSTATS_JWT_PUBLIC_KEY=dummy
      - RTCSTATS_FILES_ENDPOINT
      - RTCSTATS_JWT_EGHT_PUBLIC_KEY=dummy
      - USERS_FILE=.data/users.json
    
    depends_on:
      rtcstats_initialize:
        condition: service_completed_successfully

  
  rtcstats_initialize:
    container_name: rtcstats_initialize
    build:
      context: ./rtcstats-initialize
      dockerfile: ./Dockerfile
    environment:
      # For AWS credentials
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_ENDPOINT_URL=http://localstack:4566

      # Localstack
      - LOCALSTACK_ENDPOINT=http://localstack:4566

      - RTCSTATS_METADATA_TABLE=rtcstats-meta-table-local
      - RTCSTATS_S3_BUCKET=jitsi-micros-rtcstats-server
      - RTCSTATS_S3_REGION=us-east-1

    depends_on:
      - localstack


  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - 4566:4566            # LocalStack Gateway
      - 4510-4559:4510-4559  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - SERVICES=lambda,iam,logs,s3,dynamodb,firehose
      - DEBUG=${DEBUG:-1}
      - AWS_DEFAULT_REGION=us-east-1

      # For AWS credentials
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_OUTPUT=json
      - AWS_ENDPOINT_URL=http://localstack:4566

    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
